# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 786)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 786))
        MainWindow.setStyleSheet("/* === ГЛОБАЛЬНЫЙ ФОН === */\n"
"QMainWindow, QWidget#centralwidget {\n"
"    background-color: #101828;\n"
"}\n"
"\n"
"/* === ВЕРХНЯЯ ПАНЕЛЬ (топбар) === */\n"
"QFrame#frameTopBar {\n"
"    background-color: #1E2939;\n"
"    border: 1px solid #364153;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"/* Кнопки иконок в топбаре */\n"
"QPushButton#btnTopSwitch, QPushButton#btnTopBack,\n"
"QPushButton#btnTopSettings, QPushButton#btnTopHome {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton#btnTopSwitch:hover, QPushButton#btnTopBack:hover,\n"
"QPushButton#btnTopSettings:hover, QPushButton#btnTopHome:hover {\n"
"    background-color: #334155;\n"
"}\n"
"QPushButton#btnTopSwitch:pressed, QPushButton#btnTopBack:pressed,\n"
"QPushButton#btnTopSettings:pressed, QPushButton#btnTopHome:pressed {\n"
"    background-color: #475569;\n"
"}\n"
"\n"
"/* Текст в топбаре (текущий режим) */\n"
"QLabel#lblCurrentMainMode {\n"
"    color: #818181;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: 400;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* === СТРАНИЦА ВЫБОРА РЕЖИМА (проволока/порошок) === */\n"
"QPushButton#btnWire, QPushButton#btnPowder {\n"
"    background-color: #1E2939;\n"
"    color: white;\n"
"    border: 1px solid #364153;\n"
"    border-radius: 15px;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 28px;\n"
"    font-weight: 400;\n"
"    min-height: 180px;\n"
"    min-width: 300px;\n"
"}\n"
"QPushButton#btnWire:hover, QPushButton#btnPowder:hover {\n"
"    background-color: #334155;\n"
"}\n"
"QPushButton#btnWire:pressed, QPushButton#btnPowder:pressed {\n"
"    background-color: #1E2939;\n"
"}\n"
"\n"
"/* Кнопка Выход */\n"
"QPushButton#btnExit {\n"
"    background-color: #EF4444;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 20px;\n"
"    font-weight: 400;\n"
"    min-height: 50px;\n"
"    min-width: 180px;\n"
"}\n"
"QPushButton#btnExit:hover {\n"
"    background-color: #DC2626;\n"
"}\n"
"QPushButton#btnExit:pressed {\n"
"    background-color: #B91C1C;\n"
"}\n"
"\n"
"/* === СТРАНИЦА УПРАВЛЕНИЯ (page_2) === */\n"
"/* Шапка (frameHeader) */\n"
"QFrame#frameHeader {\n"
"    background-color: transparent;\n"
"    margin: 0px;\n"
"    padding: 10px 20px;\n"
"}\n"
"QLabel#lblSystemStatus {\n"
"    background-color: transparent;\n"
"    color: #FFFFFF;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: 400;\n"
"}\n"
"QLabel#lblCurrentMode {\n"
"    color: #818181;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: 400;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Кнопки СТАРТ и СТОП */\n"
"QPushButton#btnStart {\n"
"    background-color: #22C55E;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 20px;\n"
"    font-weight: 400;\n"
"    min-width: 180px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton#btnStart:hover {\n"
"    background-color: #16A34A;\n"
"}\n"
"QPushButton#btnStart:pressed {\n"
"    background-color: #15803D;\n"
"}\n"
"QPushButton#btnStop {\n"
"    background-color: #EF4444;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 20px;\n"
"    font-weight: 400;\n"
"    min-width: 180px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton#btnStop:hover {\n"
"    background-color: #DC2626;\n"
"}\n"
"QPushButton#btnStop:pressed {\n"
"    background-color: #B91C1C;\n"
"}\n"
"\n"
"/* === КАРТОЧКИ \"ЗАЖИГАНИЕ ДУГИ\" И \"СИСТЕМА ПОДАЧИ\" (layoutModules) === */\n"
"QFrame#frameIgnition, QFrame#frameFeeding {\n"
"    background-color: #1E2939;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #364153;\n"
"    padding: 15px;\n"
"}\n"
"/* Заголовки внутри карточек */\n"
"QFrame#frameIgnition QLabel:first-child, \n"
"QFrame#frameFeeding QLabel:first-child {\n"
"    color: #FFFFFF;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 22px;\n"
"    font-weight: 500;\n"
"}\n"
"/* Строка \"Система:Активна\" (единый стиль, т.к. в .ui это один QLabel) */\n"
"QLabel#label_25, QLabel#label {\n"
"    color: #818181;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 18px;\n"
"    font-weight: 400;\n"
"    background-color: transparent;\n"
"}\n"
"/* Чекбоксы внутри карточек модулей – стилизуем как переключатели iOS */\n"
"QFrame#frameIgnition QCheckBox, \n"
"QFrame#frameFeeding QCheckBox {\n"
"    spacing: 8px;\n"
"}\n"
"QFrame#frameIgnition QCheckBox::indicator,\n"
"QFrame#frameFeeding QCheckBox::indicator {\n"
"    width: 51px;\n"
"    height: 31px;\n"
"    border-radius: 100px;\n"
"    background-color: #64748B;\n"
"}\n"
"QFrame#frameIgnition QCheckBox::indicator:checked,\n"
"QFrame#frameFeeding QCheckBox::indicator:checked {\n"
"    background-color: #007AFF;\n"
"}\n"
"QFrame#frameIgnition QCheckBox, \n"
"QFrame#frameFeeding QCheckBox {\n"
"    text: \"\";\n"
"}\n"
"\n"
"/* === КАРТОЧКИ ГАЗОВ === */\n"
"QFrame#framePropane_2, QFrame#frameOxygen, QFrame#frameAir,\n"
"QFrame#frameQgas_Feeder, QFrame#framePistol_Patatel {\n"
"    background-color: #1E2939;\n"
"    border-radius: 15px;\n"
"    border: none;\n"
"}\n"
"QLabel[objectName$=\"Name\"] {\n"
"    color: #818181;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"/* === БЛОКИ \"РАБОЧЕЕ ЗНАЧЕНИЕ\" И \"ТЕКУЩЕЕ ЗНАЧЕНИЕ\" (серые прямоугольники) === */\n"
"QFrame#frameWorkValue, QFrame#frameWorkValue_2, QFrame#frameWorkValue_3,\n"
"QFrame#frameWorkValue_4, QFrame#frameWorkValue_5,\n"
"QFrame#frameCurrentValue, QFrame#frameCurrentValue_2, QFrame#frameCurrentValue_3,\n"
"QFrame#frameCurrentValue_4, QFrame#frameCurrentValue_5 {\n"
"    background-color: #364153;\n"
"    border-radius: 15px;\n"
"    border: none;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* Подписи \"Рабочее значение\" и \"Текущее значение\" */\n"
"QLabel[text=\"Рабочее значение\"], QLabel[text=\"Текущее значение\"] {\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"}\n"
"QLabel[text=\"Рабочее значение\"] {\n"
"    color: #FFFFFF;\n"
"}\n"
"QLabel[text=\"Текущее значение\"] {\n"
"    color: #818181;\n"
"}\n"
"/* Значения (50.0 л/с) */\n"
"QLabel[objectName$=\"WorkWalue\"], QLabel[objectName$=\"WorkValue\"],\n"
"QLabel[objectName$=\"CurrentWalue\"], QLabel[objectName$=\"CurrentValue\"] {\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: 400;\n"
"}\n"
"QLabel[objectName$=\"WorkWalue\"], QLabel[objectName$=\"WorkValue\"] {\n"
"    color: #FFFFFF;\n"
"}\n"
"QLabel[objectName$=\"CurrentWalue\"], QLabel[objectName$=\"CurrentValue\"] {\n"
"    color: #818181;\n"
"}\n"
"\n"
"/* === КНОПКИ SET === */\n"
"QPushButton[objectName$=\"Set\"] {\n"
"    background-color: #007AFF;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: 400;\n"
"    min-width: 112px;\n"
"    min-height: 48px;\n"
"}\n"
"QPushButton[objectName$=\"Set\"]:hover {\n"
"    background-color: #005BB5;\n"
"}\n"
"QPushButton[objectName$=\"Set\"]:pressed {\n"
"    background-color: #004099;\n"
"}\n"
"\n"
"/* === КНОПКИ + и - === */\n"
"QPushButton[objectName$=\"Decrease\"], QPushButton[objectName$=\"decrease\"] {\n"
"    background-color: transparent;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 64px;\n"
"    font-weight: 400;\n"
"}\n"
"QPushButton[objectName$=\"Increase\"], QPushButton[objectName$=\"increase\"] {\n"
"    background-color: transparent;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 32px;\n"
"    font-weight: 400;\n"
"}\n"
"QPushButton[objectName$=\"Decrease\"]:hover, QPushButton[objectName$=\"Increase\"]:hover,\n"
"QPushButton[objectName$=\"decrease\"]:hover, QPushButton[objectName$=\"increase\"]:hover {\n"
"    color: #94A3B8;\n"
"}\n"
"\n"
"/* === ПЕРЕКЛЮЧАТЕЛИ iOS (QCheckBox для газов и модулей) === */\n"
"QCheckBox[objectName$=\"Switch\"] {\n"
"    spacing: 8px;\n"
"}\n"
"QCheckBox[objectName$=\"Switch\"]::indicator {\n"
"    width: 51px;\n"
"    height: 31px;\n"
"    border-radius: 100px;\n"
"}\n"
"QCheckBox[objectName$=\"Switch\"]::indicator:unchecked {\n"
"    background-color: #64748B;\n"
"}\n"
"QCheckBox[objectName$=\"Switch\"]::indicator:checked {\n"
"    background-color: #007AFF;\n"
"}\n"
"QCheckBox[objectName$=\"Switch\"] {\n"
"    text: \"\";\n"
"}\n"
"\n"
"/* === ДОПОЛНИТЕЛЬНО: стиль для текста \"Активна\" / \"Система:\" (если разделите на два лейбла) === */\n"
"QLabel[text=\"Активна\"] {\n"
"    color: #FFFFFF;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 18px;\n"
"}\n"
"QLabel[text=\"Система:\"] {\n"
"    color: #818181;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === СКРОЛЛБАРЫ === */\n"
"QScrollBar:vertical {\n"
"    background: #1E2939;\n"
"    width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #475569;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #64748B;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"/* === ЭКРАН РЕЦЕПТОВ (page_3) === */\n"
"QFrame#frameTopBar_3 {\n"
"    background-color: #1E2939;\n"
"    border: 1px solid #364153;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"QPushButton#btnRecipesBack {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    color: #FFFFFF;\n"
"    font-size: 20px;\n"
"}\n"
"QPushButton#btnRecipesBack:hover { background-color: #334155; }\n"
"QPushButton#btnRecipesBack:pressed { background-color: #475569; }\n"
"QLabel#lblRecipesTitle {\n"
"    color: #FFFFFF;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: 500;\n"
"    background-color: transparent;\n"
"}\n"
"QTableWidget#tableRecipes {\n"
"    background-color: #1E2939;\n"
"    alternate-background-color: #253347;\n"
"    color: #FFFFFF;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 18px;\n"
"    border: 1px solid #364153;\n"
"    border-radius: 12px;\n"
"    gridline-color: #364153;\n"
"    selection-background-color: #FFFFFF;\n"
"    selection-color: #101828;\n"
"}\n"
"QTableWidget#tableRecipes QHeaderView::section {\n"
"    background-color: #364153;\n"
"    color: #818181;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    border: none;\n"
"    padding: 8px;\n"
"}\n"
"QTableWidget#tableRecipes::item { padding: 10px; border: none; }\n"
"QTableWidget#tableRecipes::item:selected {\n"
"    background-color: #FFFFFF;\n"
"    color: #101828;\n"
"}\n"
"QPushButton#btnRecipeUp, QPushButton#btnRecipeDown {\n"
"    background-color: #1E2939;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #364153;\n"
"    border-radius: 12px;\n"
"    font-size: 24px;\n"
"}\n"
"QPushButton#btnRecipeUp:hover, QPushButton#btnRecipeDown:hover { background-color: #334155; }\n"
"QPushButton#btnRecipeUp:pressed, QPushButton#btnRecipeDown:pressed { background-color: #475569; }\n"
"QPushButton#btnRecipeSelect {\n"
"    background-color: #22C55E;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton#btnRecipeSelect:hover { background-color: #16A34A; }\n"
"QPushButton#btnRecipeSelect:pressed { background-color: #15803D; }")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget, QWidget[objectName^=\"page\"] {\n"
"    background-color: #0F172A;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameTopBar = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameTopBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameTopBar.setStyleSheet("")
        self.frameTopBar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameTopBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameTopBar.setObjectName("frameTopBar")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frameTopBar)
        self.horizontalLayout_18.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btnTopSwitch = QtWidgets.QPushButton(parent=self.frameTopBar)
        self.btnTopSwitch.setMinimumSize(QtCore.QSize(0, 0))
        self.btnTopSwitch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/On_button_light.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTopSwitch.setIcon(icon)
        self.btnTopSwitch.setIconSize(QtCore.QSize(32, 32))
        self.btnTopSwitch.setObjectName("btnTopSwitch")
        self.horizontalLayout_18.addWidget(self.btnTopSwitch)
        self.btnTopBack = QtWidgets.QPushButton(parent=self.frameTopBar)
        self.btnTopBack.setMinimumSize(QtCore.QSize(0, 0))
        self.btnTopBack.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Arrow_left.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTopBack.setIcon(icon1)
        self.btnTopBack.setIconSize(QtCore.QSize(32, 32))
        self.btnTopBack.setObjectName("btnTopBack")
        self.horizontalLayout_18.addWidget(self.btnTopBack)
        self.btnTopSettings = QtWidgets.QPushButton(parent=self.frameTopBar)
        self.btnTopSettings.setMinimumSize(QtCore.QSize(0, 0))
        self.btnTopSettings.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnTopSettings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Setting_line_light.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTopSettings.setIcon(icon2)
        self.btnTopSettings.setIconSize(QtCore.QSize(32, 32))
        self.btnTopSettings.setObjectName("btnTopSettings")
        self.horizontalLayout_18.addWidget(self.btnTopSettings)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.lblCurrentMainMode = QtWidgets.QLabel(parent=self.frameTopBar)
        self.lblCurrentMainMode.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCurrentMainMode.setObjectName("lblCurrentMainMode")
        self.horizontalLayout_18.addWidget(self.lblCurrentMainMode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.btnTopHome = QtWidgets.QPushButton(parent=self.frameTopBar)
        self.btnTopHome.setMinimumSize(QtCore.QSize(0, 0))
        self.btnTopHome.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnTopHome.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Home_light.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTopHome.setIcon(icon3)
        self.btnTopHome.setIconSize(QtCore.QSize(32, 32))
        self.btnTopHome.setObjectName("btnTopHome")
        self.horizontalLayout_18.addWidget(self.btnTopHome)
        self.horizontalLayout_18.setStretch(3, 1)
        self.horizontalLayout_18.setStretch(5, 1)
        self.verticalLayout.addWidget(self.frameTopBar)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(60)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnWire = QtWidgets.QPushButton(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWire.sizePolicy().hasHeightForWidth())
        self.btnWire.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        self.btnWire.setFont(font)
        self.btnWire.setStyleSheet("QPushButton {\n"
"    background-color: #334155; /* Цвет кнопок из макета */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    font: bold 22pt \"Inter\", \"Arial\"; /* Крупный шрифт */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1E293B; /* Затемнение при нажатии */\n"
"}")
        self.btnWire.setObjectName("btnWire")
        self.horizontalLayout_5.addWidget(self.btnWire)
        self.btnPowder = QtWidgets.QPushButton(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPowder.sizePolicy().hasHeightForWidth())
        self.btnPowder.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        self.btnPowder.setFont(font)
        self.btnPowder.setStyleSheet("QPushButton {\n"
"    background-color: #334155; /* Цвет кнопок из макета */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    font: bold 22pt \"Inter\", \"Arial\"; /* Крупный шрифт */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1E293B; /* Затемнение при нажатии */\n"
"}")
        self.btnPowder.setObjectName("btnPowder")
        self.horizontalLayout_5.addWidget(self.btnPowder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.btnExit = QtWidgets.QPushButton(parent=self.page)
        self.btnExit.setMinimumSize(QtCore.QSize(200, 60))
        self.btnExit.setStyleSheet("QPushButton {\n"
"    background-color: #EF4444; /* Красный цвет из Figma */\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font: bold 16pt \"Inter\", \"Arial\";\n"
"    min-height: 60px; /* Чтобы она не была слишком тонкой */\n"
"    min-width: 200px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #B91C1C;\n"
"}")
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_6.addWidget(self.btnExit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameHeader = QtWidgets.QFrame(parent=self.page_2)
        self.frameHeader.setStyleSheet("background-color: rgb(30, 41, 57);")
        self.frameHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frameHeader)
        self.verticalLayout_28.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_28.setSpacing(4)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblSystemStatus = QtWidgets.QLabel(parent=self.frameHeader)
        self.lblSystemStatus.setObjectName("lblSystemStatus")
        self.layoutHeader.addWidget(self.lblSystemStatus)
        self.ledSystemStatus = QtWidgets.QLabel(parent=self.frameHeader)
        self.ledSystemStatus.setMinimumSize(QtCore.QSize(45, 0))
        self.ledSystemStatus.setStyleSheet("QLabel#ledSystemStatus {\n"
"    background-color: #22C55E; /* зелёный – норма */\n"
"    border-radius: 15px; /* половина ширины/высоты для круга */\n"
"}\n"
"QLabel#ledSystemStatus[status=\"error\"] {\n"
"    background-color: #EF4444; /* красный – ошибка */\n"
"}")
        self.ledSystemStatus.setText("")
        self.ledSystemStatus.setObjectName("ledSystemStatus")
        self.layoutHeader.addWidget(self.ledSystemStatus)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem7)
        self.btnStart = QtWidgets.QPushButton(parent=self.frameHeader)
        self.btnStart.setMinimumSize(QtCore.QSize(180, 50))
        self.btnStart.setStyleSheet("background-color: rgb(34, 197, 94);")
        self.btnStart.setObjectName("btnStart")
        self.layoutHeader.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(parent=self.frameHeader)
        self.btnStop.setMinimumSize(QtCore.QSize(180, 50))
        self.btnStop.setStyleSheet("background-color: rgb(239, 68, 68);")
        self.btnStop.setObjectName("btnStop")
        self.layoutHeader.addWidget(self.btnStop)
        self.verticalLayout_28.addLayout(self.layoutHeader)
        self.lblCurrentMode = QtWidgets.QLabel(parent=self.frameHeader)
        self.lblCurrentMode.setStyleSheet("background-color: rgb(54, 65, 83);\n"
"border-radius: 6px;")
        self.lblCurrentMode.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCurrentMode.setObjectName("lblCurrentMode")
        self.verticalLayout_28.addWidget(self.lblCurrentMode)
        self.verticalLayout_3.addWidget(self.frameHeader)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.layoutModules = QtWidgets.QHBoxLayout()
        self.layoutModules.setSpacing(30)
        self.layoutModules.setObjectName("layoutModules")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutModules.addItem(spacerItem9)
        self.frameIgnition = QtWidgets.QFrame(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameIgnition.sizePolicy().hasHeightForWidth())
        self.frameIgnition.setSizePolicy(sizePolicy)
        self.frameIgnition.setMinimumSize(QtCore.QSize(450, 0))
        self.frameIgnition.setStyleSheet("/* Rectangle 5 */\n"
"\n"
"\n"
"border-radius: 15px;\n"
"")
        self.frameIgnition.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameIgnition.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameIgnition.setObjectName("frameIgnition")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameIgnition)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_26 = QtWidgets.QLabel(parent=self.frameIgnition)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_22.addWidget(self.label_26)
        self.checkBoxArcIgnition = QtWidgets.QCheckBox(parent=self.frameIgnition)
        self.checkBoxArcIgnition.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkBoxArcIgnition.setText("")
        self.checkBoxArcIgnition.setObjectName("checkBoxArcIgnition")
        self.horizontalLayout_22.addWidget(self.checkBoxArcIgnition)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.label_25 = QtWidgets.QLabel(parent=self.frameIgnition)
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.layoutModules.addWidget(self.frameIgnition)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutModules.addItem(spacerItem10)
        self.frameFeeding = QtWidgets.QFrame(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameFeeding.sizePolicy().hasHeightForWidth())
        self.frameFeeding.setSizePolicy(sizePolicy)
        self.frameFeeding.setMinimumSize(QtCore.QSize(450, 0))
        self.frameFeeding.setStyleSheet("border-radius: 15px;")
        self.frameFeeding.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameFeeding.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameFeeding.setObjectName("frameFeeding")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameFeeding)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_2 = QtWidgets.QLabel(parent=self.frameFeeding)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_21.addWidget(self.label_2)
        self.checkBoxFeedingSystem = QtWidgets.QCheckBox(parent=self.frameFeeding)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxFeedingSystem.setFont(font)
        self.checkBoxFeedingSystem.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkBoxFeedingSystem.setText("")
        self.checkBoxFeedingSystem.setObjectName("checkBoxFeedingSystem")
        self.horizontalLayout_21.addWidget(self.checkBoxFeedingSystem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.label = QtWidgets.QLabel(parent=self.frameFeeding)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.layoutModules.addWidget(self.frameFeeding)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutModules.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.layoutModules)
        spacerItem12 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.layoutGasGrid = QtWidgets.QGridLayout()
        self.layoutGasGrid.setHorizontalSpacing(6)
        self.layoutGasGrid.setVerticalSpacing(0)
        self.layoutGasGrid.setObjectName("layoutGasGrid")
        self.frameOxygen = QtWidgets.QFrame(parent=self.page_2)
        self.frameOxygen.setStyleSheet("")
        self.frameOxygen.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameOxygen.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameOxygen.setObjectName("frameOxygen")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frameOxygen)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.oxygenHeading = QtWidgets.QHBoxLayout()
        self.oxygenHeading.setObjectName("oxygenHeading")
        self.lblOxygenName = QtWidgets.QLabel(parent=self.frameOxygen)
        self.lblOxygenName.setObjectName("lblOxygenName")
        self.oxygenHeading.addWidget(self.lblOxygenName)
        self.checkBoxOxygenSwitch = QtWidgets.QCheckBox(parent=self.frameOxygen)
        self.checkBoxOxygenSwitch.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkBoxOxygenSwitch.setText("")
        self.checkBoxOxygenSwitch.setObjectName("checkBoxOxygenSwitch")
        self.oxygenHeading.addWidget(self.checkBoxOxygenSwitch)
        self.verticalLayout_13.addLayout(self.oxygenHeading)
        self.frameWorkValue_2 = QtWidgets.QFrame(parent=self.frameOxygen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameWorkValue_2.sizePolicy().hasHeightForWidth())
        self.frameWorkValue_2.setSizePolicy(sizePolicy)
        self.frameWorkValue_2.setStyleSheet("")
        self.frameWorkValue_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameWorkValue_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameWorkValue_2.setObjectName("frameWorkValue_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frameWorkValue_2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_17 = QtWidgets.QLabel(parent=self.frameWorkValue_2)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_20.addWidget(self.label_17)
        self.lblOxygenWorkWalue = QtWidgets.QLabel(parent=self.frameWorkValue_2)
        self.lblOxygenWorkWalue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblOxygenWorkWalue.setObjectName("lblOxygenWorkWalue")
        self.verticalLayout_20.addWidget(self.lblOxygenWorkWalue)
        self.verticalLayout_13.addWidget(self.frameWorkValue_2)
        self.frameCurrentValue_2 = QtWidgets.QFrame(parent=self.frameOxygen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameCurrentValue_2.sizePolicy().hasHeightForWidth())
        self.frameCurrentValue_2.setSizePolicy(sizePolicy)
        self.frameCurrentValue_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCurrentValue_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCurrentValue_2.setObjectName("frameCurrentValue_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frameCurrentValue_2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_18 = QtWidgets.QLabel(parent=self.frameCurrentValue_2)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_21.addWidget(self.label_18)
        self.lblOxygenCurrentValue = QtWidgets.QLabel(parent=self.frameCurrentValue_2)
        self.lblOxygenCurrentValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblOxygenCurrentValue.setObjectName("lblOxygenCurrentValue")
        self.verticalLayout_21.addWidget(self.lblOxygenCurrentValue)
        self.verticalLayout_13.addWidget(self.frameCurrentValue_2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem13)
        self.btnOxygenSet = QtWidgets.QPushButton(parent=self.frameOxygen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOxygenSet.sizePolicy().hasHeightForWidth())
        self.btnOxygenSet.setSizePolicy(sizePolicy)
        self.btnOxygenSet.setObjectName("btnOxygenSet")
        self.verticalLayout_13.addWidget(self.btnOxygenSet)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(0, 15, 0, 15)
        self.horizontalLayout_15.setSpacing(15)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btnOxygenDecrease = QtWidgets.QPushButton(parent=self.frameOxygen)
        self.btnOxygenDecrease.setObjectName("btnOxygenDecrease")
        self.horizontalLayout_15.addWidget(self.btnOxygenDecrease)
        self.bntOxygenIncrease = QtWidgets.QPushButton(parent=self.frameOxygen)
        self.bntOxygenIncrease.setObjectName("bntOxygenIncrease")
        self.horizontalLayout_15.addWidget(self.bntOxygenIncrease)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.layoutGasGrid.addWidget(self.frameOxygen, 0, 1, 1, 1)
        self.framePistol_Patatel = QtWidgets.QFrame(parent=self.page_2)
        self.framePistol_Patatel.setStyleSheet("")
        self.framePistol_Patatel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.framePistol_Patatel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.framePistol_Patatel.setObjectName("framePistol_Patatel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.framePistol_Patatel)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.airPistol_PalatelHeading = QtWidgets.QHBoxLayout()
        self.airPistol_PalatelHeading.setObjectName("airPistol_PalatelHeading")
        self.lblPistol_PatatelName = QtWidgets.QLabel(parent=self.framePistol_Patatel)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(False)
        self.lblPistol_PatatelName.setFont(font)
        self.lblPistol_PatatelName.setObjectName("lblPistol_PatatelName")
        self.airPistol_PalatelHeading.addWidget(self.lblPistol_PatatelName)
        self.checkBoxPistol_PatatelSwitch = QtWidgets.QCheckBox(parent=self.framePistol_Patatel)
        self.checkBoxPistol_PatatelSwitch.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkBoxPistol_PatatelSwitch.setText("")
        self.checkBoxPistol_PatatelSwitch.setObjectName("checkBoxPistol_PatatelSwitch")
        self.airPistol_PalatelHeading.addWidget(self.checkBoxPistol_PatatelSwitch)
        self.verticalLayout_4.addLayout(self.airPistol_PalatelHeading)
        self.frameWorkValue_5 = QtWidgets.QFrame(parent=self.framePistol_Patatel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameWorkValue_5.sizePolicy().hasHeightForWidth())
        self.frameWorkValue_5.setSizePolicy(sizePolicy)
        self.frameWorkValue_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameWorkValue_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameWorkValue_5.setObjectName("frameWorkValue_5")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frameWorkValue_5)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_23 = QtWidgets.QLabel(parent=self.frameWorkValue_5)
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_26.addWidget(self.label_23)
        self.lblPistol_PatatelWorkWalue = QtWidgets.QLabel(parent=self.frameWorkValue_5)
        self.lblPistol_PatatelWorkWalue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPistol_PatatelWorkWalue.setObjectName("lblPistol_PatatelWorkWalue")
        self.verticalLayout_26.addWidget(self.lblPistol_PatatelWorkWalue)
        self.verticalLayout_4.addWidget(self.frameWorkValue_5)
        self.frameCurrentValue_5 = QtWidgets.QFrame(parent=self.framePistol_Patatel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameCurrentValue_5.sizePolicy().hasHeightForWidth())
        self.frameCurrentValue_5.setSizePolicy(sizePolicy)
        self.frameCurrentValue_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCurrentValue_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCurrentValue_5.setObjectName("frameCurrentValue_5")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frameCurrentValue_5)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_24 = QtWidgets.QLabel(parent=self.frameCurrentValue_5)
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_27.addWidget(self.label_24)
        self.lblPistol_PatatelCurrentWalue = QtWidgets.QLabel(parent=self.frameCurrentValue_5)
        self.lblPistol_PatatelCurrentWalue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPistol_PatatelCurrentWalue.setObjectName("lblPistol_PatatelCurrentWalue")
        self.verticalLayout_27.addWidget(self.lblPistol_PatatelCurrentWalue)
        self.verticalLayout_4.addWidget(self.frameCurrentValue_5)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.btnPistol_PatatelSet = QtWidgets.QPushButton(parent=self.framePistol_Patatel)
        self.btnPistol_PatatelSet.setObjectName("btnPistol_PatatelSet")
        self.verticalLayout_4.addWidget(self.btnPistol_PatatelSet)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 15, 0, 15)
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnPistol_PatatelDecrease = QtWidgets.QPushButton(parent=self.framePistol_Patatel)
        self.btnPistol_PatatelDecrease.setObjectName("btnPistol_PatatelDecrease")
        self.horizontalLayout_7.addWidget(self.btnPistol_PatatelDecrease)
        self.btnPistol_PatatelIncrease = QtWidgets.QPushButton(parent=self.framePistol_Patatel)
        self.btnPistol_PatatelIncrease.setObjectName("btnPistol_PatatelIncrease")
        self.horizontalLayout_7.addWidget(self.btnPistol_PatatelIncrease)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.layoutGasGrid.addWidget(self.framePistol_Patatel, 0, 4, 1, 1)
        self.framePropane_2 = QtWidgets.QFrame(parent=self.page_2)
        self.framePropane_2.setStyleSheet("")
        self.framePropane_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.framePropane_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.framePropane_2.setObjectName("framePropane_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.framePropane_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.propaneHeading = QtWidgets.QHBoxLayout()
        self.propaneHeading.setObjectName("propaneHeading")
        self.lblPropaneName = QtWidgets.QLabel(parent=self.framePropane_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(False)
        self.lblPropaneName.setFont(font)
        self.lblPropaneName.setObjectName("lblPropaneName")
        self.propaneHeading.addWidget(self.lblPropaneName)
        self.checkBoxPropaneSwitch = QtWidgets.QCheckBox(parent=self.framePropane_2)
        self.checkBoxPropaneSwitch.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkBoxPropaneSwitch.setText("")
        self.checkBoxPropaneSwitch.setChecked(False)
        self.checkBoxPropaneSwitch.setObjectName("checkBoxPropaneSwitch")
        self.propaneHeading.addWidget(self.checkBoxPropaneSwitch)
        self.verticalLayout_12.addLayout(self.propaneHeading)
        self.frameWorkValue = QtWidgets.QFrame(parent=self.framePropane_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameWorkValue.sizePolicy().hasHeightForWidth())
        self.frameWorkValue.setSizePolicy(sizePolicy)
        self.frameWorkValue.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameWorkValue.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameWorkValue.setObjectName("frameWorkValue")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frameWorkValue)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_3 = QtWidgets.QLabel(parent=self.frameWorkValue)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_16.addWidget(self.label_3)
        self.lblPropaneWorkWalue = QtWidgets.QLabel(parent=self.frameWorkValue)
        self.lblPropaneWorkWalue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPropaneWorkWalue.setObjectName("lblPropaneWorkWalue")
        self.verticalLayout_16.addWidget(self.lblPropaneWorkWalue)
        self.verticalLayout_12.addWidget(self.frameWorkValue)
        self.frameCurrentValue = QtWidgets.QFrame(parent=self.framePropane_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameCurrentValue.sizePolicy().hasHeightForWidth())
        self.frameCurrentValue.setSizePolicy(sizePolicy)
        self.frameCurrentValue.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCurrentValue.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCurrentValue.setObjectName("frameCurrentValue")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frameCurrentValue)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_4 = QtWidgets.QLabel(parent=self.frameCurrentValue)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_17.addWidget(self.label_4)
        self.lblPropaneCurrentValue = QtWidgets.QLabel(parent=self.frameCurrentValue)
        self.lblPropaneCurrentValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPropaneCurrentValue.setObjectName("lblPropaneCurrentValue")
        self.verticalLayout_17.addWidget(self.lblPropaneCurrentValue)
        self.verticalLayout_12.addWidget(self.frameCurrentValue)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem15)
        self.btnPropaneSet = QtWidgets.QPushButton(parent=self.framePropane_2)
        self.btnPropaneSet.setObjectName("btnPropaneSet")
        self.verticalLayout_12.addWidget(self.btnPropaneSet)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(0, 15, 0, 15)
        self.horizontalLayout_14.setSpacing(15)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btnPropaneDecrease = QtWidgets.QPushButton(parent=self.framePropane_2)
        self.btnPropaneDecrease.setObjectName("btnPropaneDecrease")
        self.horizontalLayout_14.addWidget(self.btnPropaneDecrease)
        self.bntPropaneIncrease = QtWidgets.QPushButton(parent=self.framePropane_2)
        self.bntPropaneIncrease.setObjectName("bntPropaneIncrease")
        self.horizontalLayout_14.addWidget(self.bntPropaneIncrease)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.layoutGasGrid.addWidget(self.framePropane_2, 0, 0, 1, 1)
        self.frameAir = QtWidgets.QFrame(parent=self.page_2)
        self.frameAir.setStyleSheet("")
        self.frameAir.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameAir.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameAir.setObjectName("frameAir")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frameAir)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.airHeading = QtWidgets.QHBoxLayout()
        self.airHeading.setObjectName("airHeading")
        self.lblAirName = QtWidgets.QLabel(parent=self.frameAir)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(False)
        self.lblAirName.setFont(font)
        self.lblAirName.setObjectName("lblAirName")
        self.airHeading.addWidget(self.lblAirName)
        self.checkBoxAirSwitch = QtWidgets.QCheckBox(parent=self.frameAir)
        self.checkBoxAirSwitch.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkBoxAirSwitch.setText("")
        self.checkBoxAirSwitch.setObjectName("checkBoxAirSwitch")
        self.airHeading.addWidget(self.checkBoxAirSwitch)
        self.verticalLayout_14.addLayout(self.airHeading)
        self.frameWorkValue_3 = QtWidgets.QFrame(parent=self.frameAir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameWorkValue_3.sizePolicy().hasHeightForWidth())
        self.frameWorkValue_3.setSizePolicy(sizePolicy)
        self.frameWorkValue_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameWorkValue_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameWorkValue_3.setObjectName("frameWorkValue_3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frameWorkValue_3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_19 = QtWidgets.QLabel(parent=self.frameWorkValue_3)
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_22.addWidget(self.label_19)
        self.lblAirWorkWalue = QtWidgets.QLabel(parent=self.frameWorkValue_3)
        self.lblAirWorkWalue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAirWorkWalue.setObjectName("lblAirWorkWalue")
        self.verticalLayout_22.addWidget(self.lblAirWorkWalue)
        self.verticalLayout_14.addWidget(self.frameWorkValue_3)
        self.frameCurrentValue_3 = QtWidgets.QFrame(parent=self.frameAir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameCurrentValue_3.sizePolicy().hasHeightForWidth())
        self.frameCurrentValue_3.setSizePolicy(sizePolicy)
        self.frameCurrentValue_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCurrentValue_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCurrentValue_3.setObjectName("frameCurrentValue_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frameCurrentValue_3)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_20 = QtWidgets.QLabel(parent=self.frameCurrentValue_3)
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_23.addWidget(self.label_20)
        self.lblAirCurrentValue = QtWidgets.QLabel(parent=self.frameCurrentValue_3)
        self.lblAirCurrentValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAirCurrentValue.setObjectName("lblAirCurrentValue")
        self.verticalLayout_23.addWidget(self.lblAirCurrentValue)
        self.verticalLayout_14.addWidget(self.frameCurrentValue_3)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem16)
        self.btnAirSet = QtWidgets.QPushButton(parent=self.frameAir)
        self.btnAirSet.setObjectName("btnAirSet")
        self.verticalLayout_14.addWidget(self.btnAirSet)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(0, 15, 0, 15)
        self.horizontalLayout_16.setSpacing(15)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btnAirDecrease = QtWidgets.QPushButton(parent=self.frameAir)
        self.btnAirDecrease.setObjectName("btnAirDecrease")
        self.horizontalLayout_16.addWidget(self.btnAirDecrease)
        self.bntAirIncrease = QtWidgets.QPushButton(parent=self.frameAir)
        self.bntAirIncrease.setObjectName("bntAirIncrease")
        self.horizontalLayout_16.addWidget(self.bntAirIncrease)
        self.verticalLayout_14.addLayout(self.horizontalLayout_16)
        self.layoutGasGrid.addWidget(self.frameAir, 0, 2, 1, 1)
        self.frameQgas_Feeder = QtWidgets.QFrame(parent=self.page_2)
        self.frameQgas_Feeder.setMinimumSize(QtCore.QSize(0, 400))
        self.frameQgas_Feeder.setStyleSheet("")
        self.frameQgas_Feeder.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameQgas_Feeder.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameQgas_Feeder.setObjectName("frameQgas_Feeder")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frameQgas_Feeder)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.airQgas_FeederHeading = QtWidgets.QHBoxLayout()
        self.airQgas_FeederHeading.setObjectName("airQgas_FeederHeading")
        self.lblQgas_FeederName = QtWidgets.QLabel(parent=self.frameQgas_Feeder)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(False)
        self.lblQgas_FeederName.setFont(font)
        self.lblQgas_FeederName.setObjectName("lblQgas_FeederName")
        self.airQgas_FeederHeading.addWidget(self.lblQgas_FeederName)
        self.checkBoxQgas_FeederSwitch = QtWidgets.QCheckBox(parent=self.frameQgas_Feeder)
        self.checkBoxQgas_FeederSwitch.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkBoxQgas_FeederSwitch.setText("")
        self.checkBoxQgas_FeederSwitch.setObjectName("checkBoxQgas_FeederSwitch")
        self.airQgas_FeederHeading.addWidget(self.checkBoxQgas_FeederSwitch)
        self.verticalLayout_15.addLayout(self.airQgas_FeederHeading)
        self.frameWorkValue_4 = QtWidgets.QFrame(parent=self.frameQgas_Feeder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameWorkValue_4.sizePolicy().hasHeightForWidth())
        self.frameWorkValue_4.setSizePolicy(sizePolicy)
        self.frameWorkValue_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameWorkValue_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameWorkValue_4.setObjectName("frameWorkValue_4")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frameWorkValue_4)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_21 = QtWidgets.QLabel(parent=self.frameWorkValue_4)
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_24.addWidget(self.label_21)
        self.lblQgas_FeederWorkWalue = QtWidgets.QLabel(parent=self.frameWorkValue_4)
        self.lblQgas_FeederWorkWalue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblQgas_FeederWorkWalue.setObjectName("lblQgas_FeederWorkWalue")
        self.verticalLayout_24.addWidget(self.lblQgas_FeederWorkWalue)
        self.verticalLayout_15.addWidget(self.frameWorkValue_4)
        self.frameCurrentValue_4 = QtWidgets.QFrame(parent=self.frameQgas_Feeder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameCurrentValue_4.sizePolicy().hasHeightForWidth())
        self.frameCurrentValue_4.setSizePolicy(sizePolicy)
        self.frameCurrentValue_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCurrentValue_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCurrentValue_4.setObjectName("frameCurrentValue_4")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frameCurrentValue_4)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_22 = QtWidgets.QLabel(parent=self.frameCurrentValue_4)
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_25.addWidget(self.label_22)
        self.lblQgas_FeederCurrentWalue = QtWidgets.QLabel(parent=self.frameCurrentValue_4)
        self.lblQgas_FeederCurrentWalue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblQgas_FeederCurrentWalue.setObjectName("lblQgas_FeederCurrentWalue")
        self.verticalLayout_25.addWidget(self.lblQgas_FeederCurrentWalue)
        self.verticalLayout_15.addWidget(self.frameCurrentValue_4)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem17)
        self.btnQgas_FeederSet = QtWidgets.QPushButton(parent=self.frameQgas_Feeder)
        self.btnQgas_FeederSet.setObjectName("btnQgas_FeederSet")
        self.verticalLayout_15.addWidget(self.btnQgas_FeederSet)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(0, 15, 0, 15)
        self.horizontalLayout_17.setSpacing(15)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btnQgas_FeederDecrease = QtWidgets.QPushButton(parent=self.frameQgas_Feeder)
        self.btnQgas_FeederDecrease.setObjectName("btnQgas_FeederDecrease")
        self.horizontalLayout_17.addWidget(self.btnQgas_FeederDecrease)
        self.bntQgas_FeederIncrease = QtWidgets.QPushButton(parent=self.frameQgas_Feeder)
        self.bntQgas_FeederIncrease.setObjectName("bntQgas_FeederIncrease")
        self.horizontalLayout_17.addWidget(self.bntQgas_FeederIncrease)
        self.verticalLayout_15.addLayout(self.horizontalLayout_17)
        self.layoutGasGrid.addWidget(self.frameQgas_Feeder, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.layoutGasGrid)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_recipes = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_recipes.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_recipes.setSpacing(0)
        self.verticalLayout_recipes.setObjectName("verticalLayout_recipes")
        self.frameTopBar_3 = QtWidgets.QFrame(parent=self.page_3)
        self.frameTopBar_3.setMinimumSize(QtCore.QSize(0, 60))
        self.frameTopBar_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frameTopBar_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameTopBar_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameTopBar_3.setObjectName("frameTopBar_3")
        self.horizontalLayout_topbar3 = QtWidgets.QHBoxLayout(self.frameTopBar_3)
        self.horizontalLayout_topbar3.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_topbar3.setObjectName("horizontalLayout_topbar3")
        self.btnRecipesBack = QtWidgets.QPushButton(parent=self.frameTopBar_3)
        self.btnRecipesBack.setMinimumSize(QtCore.QSize(44, 44))
        self.btnRecipesBack.setMaximumSize(QtCore.QSize(44, 44))
        self.btnRecipesBack.setObjectName("btnRecipesBack")
        self.horizontalLayout_topbar3.addWidget(self.btnRecipesBack)
        self.lblRecipesTitle = QtWidgets.QLabel(parent=self.frameTopBar_3)
        self.lblRecipesTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblRecipesTitle.setObjectName("lblRecipesTitle")
        self.horizontalLayout_topbar3.addWidget(self.lblRecipesTitle)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_topbar3.addItem(spacerItem18)
        self.verticalLayout_recipes.addWidget(self.frameTopBar_3)
        self.horizontalLayout_recipesContent = QtWidgets.QHBoxLayout()
        self.horizontalLayout_recipesContent.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_recipesContent.setSpacing(20)
        self.horizontalLayout_recipesContent.setObjectName("horizontalLayout_recipesContent")
        self.tableRecipes = QtWidgets.QTableWidget(parent=self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableRecipes.sizePolicy().hasHeightForWidth())
        self.tableRecipes.setSizePolicy(sizePolicy)
        self.tableRecipes.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.tableRecipes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableRecipes.setColumnCount(5)
        self.tableRecipes.setObjectName("tableRecipes")
        self.tableRecipes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecipes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecipes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecipes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecipes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRecipes.setHorizontalHeaderItem(4, item)
        self.tableRecipes.horizontalHeader().setDefaultSectionSize(160)
        self.tableRecipes.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_recipesContent.addWidget(self.tableRecipes)
        self.verticalLayout_recipesSide = QtWidgets.QVBoxLayout()
        self.verticalLayout_recipesSide.setSpacing(15)
        self.verticalLayout_recipesSide.setObjectName("verticalLayout_recipesSide")
        self.btnRecipeUp = QtWidgets.QPushButton(parent=self.page_3)
        self.btnRecipeUp.setMinimumSize(QtCore.QSize(80, 80))
        self.btnRecipeUp.setObjectName("btnRecipeUp")
        self.verticalLayout_recipesSide.addWidget(self.btnRecipeUp)
        self.btnRecipeSelect = QtWidgets.QPushButton(parent=self.page_3)
        self.btnRecipeSelect.setMinimumSize(QtCore.QSize(80, 60))
        self.btnRecipeSelect.setObjectName("btnRecipeSelect")
        self.verticalLayout_recipesSide.addWidget(self.btnRecipeSelect)
        self.btnRecipeDown = QtWidgets.QPushButton(parent=self.page_3)
        self.btnRecipeDown.setMinimumSize(QtCore.QSize(80, 80))
        self.btnRecipeDown.setObjectName("btnRecipeDown")
        self.verticalLayout_recipesSide.addWidget(self.btnRecipeDown)
        self.btnAddRecipe = QtWidgets.QPushButton(parent=self.page_3)
        self.btnAddRecipe.setStyleSheet("QPushButton#btnAddRecipe {\n"
"    background-color: #1E2939;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #64748B;\n"
"    border-radius: 12px;\n"
"    font-family: \'Roboto\', \'Arial\', sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    padding: 10px;\n"
"    min-height: 60px;\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton#btnAddRecipe:hover {\n"
"    background-color: #334155;\n"
"    border: 1px solid #94A3B8;\n"
"}\n"
"QPushButton#btnAddRecipe:pressed {\n"
"    background-color: #475569;\n"
"}")
        self.btnAddRecipe.setObjectName("btnAddRecipe")
        self.verticalLayout_recipesSide.addWidget(self.btnAddRecipe)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_recipesSide.addItem(spacerItem19)
        self.horizontalLayout_recipesContent.addLayout(self.verticalLayout_recipesSide)
        self.verticalLayout_recipes.addLayout(self.horizontalLayout_recipesContent)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblCurrentMainMode.setText(_translate("MainWindow", "Проволока"))
        self.btnWire.setText(_translate("MainWindow", "Проволока"))
        self.btnPowder.setText(_translate("MainWindow", "Порошок"))
        self.btnExit.setText(_translate("MainWindow", "Выход"))
        self.lblSystemStatus.setText(_translate("MainWindow", "Система готова"))
        self.btnStart.setText(_translate("MainWindow", "Старт"))
        self.btnStop.setText(_translate("MainWindow", "Стоп"))
        self.lblCurrentMode.setText(_translate("MainWindow", "«Текущий режим: Режим 1»"))
        self.label_26.setText(_translate("MainWindow", "Зажечь дугу"))
        self.label_25.setText(_translate("MainWindow", "Система:Активна"))
        self.label_2.setText(_translate("MainWindow", "Запуск системы подачи"))
        self.label.setText(_translate("MainWindow", "Система:Активна"))
        self.lblOxygenName.setText(_translate("MainWindow", "Кислород"))
        self.label_17.setText(_translate("MainWindow", "Рабочее значение"))
        self.lblOxygenWorkWalue.setText(_translate("MainWindow", "50.0 л/с"))
        self.label_18.setText(_translate("MainWindow", "Текущее значение"))
        self.lblOxygenCurrentValue.setText(_translate("MainWindow", "50.0 л/с"))
        self.btnOxygenSet.setText(_translate("MainWindow", "Set"))
        self.btnOxygenDecrease.setText(_translate("MainWindow", "-"))
        self.bntOxygenIncrease.setText(_translate("MainWindow", "+"))
        self.lblPistol_PatatelName.setText(_translate("MainWindow", "Пистолет"))
        self.label_23.setText(_translate("MainWindow", "Рабочее значение"))
        self.lblPistol_PatatelWorkWalue.setText(_translate("MainWindow", "50.0 л/с"))
        self.label_24.setText(_translate("MainWindow", "Текущее значение"))
        self.lblPistol_PatatelCurrentWalue.setText(_translate("MainWindow", "50.0 л/с"))
        self.btnPistol_PatatelSet.setText(_translate("MainWindow", "Set"))
        self.btnPistol_PatatelDecrease.setText(_translate("MainWindow", "-"))
        self.btnPistol_PatatelIncrease.setText(_translate("MainWindow", "+"))
        self.lblPropaneName.setText(_translate("MainWindow", "Пропан"))
        self.label_3.setText(_translate("MainWindow", "Рабочее значение"))
        self.lblPropaneWorkWalue.setText(_translate("MainWindow", "50.0 л/с"))
        self.label_4.setText(_translate("MainWindow", "Текущее значение"))
        self.lblPropaneCurrentValue.setText(_translate("MainWindow", "50.0 л/с"))
        self.btnPropaneSet.setText(_translate("MainWindow", "Set"))
        self.btnPropaneDecrease.setText(_translate("MainWindow", "-"))
        self.bntPropaneIncrease.setText(_translate("MainWindow", "+"))
        self.lblAirName.setText(_translate("MainWindow", "Воздух"))
        self.label_19.setText(_translate("MainWindow", "Рабочее значение"))
        self.lblAirWorkWalue.setText(_translate("MainWindow", "50.0 л/с"))
        self.label_20.setText(_translate("MainWindow", "Текущее значение"))
        self.lblAirCurrentValue.setText(_translate("MainWindow", "50.0 л/с"))
        self.btnAirSet.setText(_translate("MainWindow", "Set"))
        self.btnAirDecrease.setText(_translate("MainWindow", "-"))
        self.bntAirIncrease.setText(_translate("MainWindow", "+"))
        self.lblQgas_FeederName.setText(_translate("MainWindow", "Q газа"))
        self.label_21.setText(_translate("MainWindow", "Рабочее значение"))
        self.lblQgas_FeederWorkWalue.setText(_translate("MainWindow", "50.0 л/с"))
        self.label_22.setText(_translate("MainWindow", "Текущее значение"))
        self.lblQgas_FeederCurrentWalue.setText(_translate("MainWindow", "50.0 л/с"))
        self.btnQgas_FeederSet.setText(_translate("MainWindow", "Set"))
        self.btnQgas_FeederDecrease.setText(_translate("MainWindow", "-"))
        self.bntQgas_FeederIncrease.setText(_translate("MainWindow", "+"))
        self.btnRecipesBack.setText(_translate("MainWindow", "←"))
        self.lblRecipesTitle.setText(_translate("MainWindow", "Рецепты"))
        item = self.tableRecipes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableRecipes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tableRecipes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Пропан"))
        item = self.tableRecipes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Кислород"))
        item = self.tableRecipes.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Скорость подачи"))
        self.btnRecipeUp.setText(_translate("MainWindow", "▲"))
        self.btnRecipeSelect.setText(_translate("MainWindow", "Выбрать режим"))
        self.btnRecipeDown.setText(_translate("MainWindow", "▼"))
        self.btnAddRecipe.setText(_translate("MainWindow", "Добавить"))
